### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by ph5i** [ppeetteerrs/obsidian-zola#45]
So, my website is being built, however, a lot of the files I have in the repo I'm building from are not being included.

Logs:
```
5:26:34 PM: Found page: networking/labs/implement-inter-vlan-routing-physical-lab.md
5:26:34 PM: Traceback (most recent call last):
5:26:34 PM:   File "__site/convert.py", line 34, in <module>
5:26:34 PM:     nodes[doc_path.abs_url] = doc_path.page_title
5:26:34 PM:   File "/opt/build/repo/__site/utils.py", line 209, in page_title
5:26:34 PM:     [
5:26:34 PM:   File "/opt/build/repo/__site/utils.py", line 210, in <listcomp>
5:26:34 PM:     item if item[0].isupper() else item.title()
5:26:34 PM: IndexError: string index out of range
5:26:34 PM: Building site...
5:26:34 PM: Checking all internal links with anchors.
5:26:34 PM: > Successfully checked 0 internal link(s) with anchors.
5:26:34 PM: -> Creating 96 pages (0 orphan) and 5 sections
5:26:35 PM: Done in 850ms.
```

The problem shouldn't be specific to the "implement-inter-vlan-routing-physical-lab.md" file. I've tried removing it and rebuilding, but the error still appears roughly at the same line (~1000-1100). Once the error appears, no more resources are being displayed as "Found", and the build finishes.

Issue #36 describes a similar problem, but it was solved:
> "My build was failing then I tried deleting the folder and recreating them and it worked."

Sadly this hasn't worked for me.

Any ideas?

**Comment by ph5i** [comment]
I previously had files with file names that included single quotes, i.e '.

Now that I've renamed the files (removing single quotes), I'm no longer having any problems deploying my website.
